// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    console.log("webitv2");
    return $("body").dblclick(function(e) {
      console.log("dblclick:");
      console.log(e.target);
      return $(e.target).append("<span id='webit-note' class='label label-info'>webitv2</span>").child().animate({
        "margin-left": "+=100px"
      }, "slow");
    });
  });

}).call(this);
