// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    $(document).ready(function() {
      return chrome.storage.local.get(function(val) {
        console.log(val["label"]);
        return $("input:radio[name='label']").val([val["label"]]);
      });
    });
    return $("button").click(function(e) {
      console.log($("input:radio[name='label']:checked").val());
      return chrome.storage.local.set({
        "label": $("input:radio[name='label']:checked").val()
      });
    });
  });

}).call(this);
