// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    var socket;
    socket = io.connect("http://localhost:3000");
    socket.emit("find recent", "hoge");
    return socket.on("send recent", function(pages) {
      var page, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = pages.length; _i < _len; _i++) {
        page = pages[_i];
        _results.push($("body").append("<div><a href='" + page.uri + "'>" + page.uri + "</a></div>"));
      }
      return _results;
    });
  });

}).call(this);
