// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    console.log("webitv2");
    return $("body").dblclick(function(e) {
      console.log("dblclick:");
      return console.log(e.target);
    });
  });

}).call(this);
